
stages:
  - build
  - test
  - deploy
  
# Building Stage - Builds the project
build:
  stage: build
  image: python:3.12
  script:
    - python mydb.py

# Testing stage: Runs unit tests 
test:
  stage: test
  image: python:3.12
  script:
    - python unittest_.py  

# Deployment stage: Deploys the application
deploy:
  stage: deploy
  script:
    - echo "Deploying application"
